flowchart
DFA0{{"DFA0 wholeStart"}}
DFA1{{"DFA1 {1}"}}
style DFA1 fill:#f9f,color:#ff0000
DFA2{{"DFA2 {1}"}}
style DFA2 fill:#f9f,color:#ff0000
DFA3{{"DFA3 {1}"}}
style DFA3 fill:#f9f,color:#ff0000
DFA0 -->|"+"|DFA1
DFA0 -->|"a"|DFA2
DFA0 -->|"b"|DFA3
