stateDiagram-v2
[*] --> [*] : c == '+'
[*] --> [*] : c == '-'
[*] --> [*] : c == '*'
[*] --> [*] : c == '/'
[*] --> [*] : c == '('
[*] --> [*] : c == ')'
[*] --> state2_1 : c ¡Ê { '0' - '9' }
[*] --> [*] : other


